CC = cl
CFLAGS = /GX /O2

EXEC = mzfdisas.exe
MAIN = mzfdisas.c
OBJS = disas.obj console.obj

all: $(EXEC)

release: all
	copy $(EXEC) w32\release

.cc.o:
	$(CC) $(CFLAGS) /c $<
	
$(EXEC): $(MAIN) $(OBJS)
	$(CC) $(CFLAGS) /o $@ $(MAIN) $(OBJS)

clean:
	del *.obj

realclean: clean
	del $(EXEC)
